spring.application.name=crud_springb_angular

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/crud_spring_angular_02
spring.datasource.username=${DB_USERNAME_POSTGRES}
spring.datasource.password=${DB_PASSWORD_POSTGRES}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.max-file-size=64MB
spring.servlet.multipart.max-request-size=64MB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=${SECURITY_USERNAME}
spring.security.user.password=${SECURITY_PASSWORD}

# JWT SECRET
jwt.secret=${JWT_SECRET}
# 10 dias em segundos, 10 dias × 24 horas × 60 minutos × 60 segundos
jwt.expiration=864000
# ou Duration.ofDays(10)

image.upload-dir=/home/brainiac/Documents/javaProjects/crudSpringBootAngular_imagens_02/backend/crud_springb_angular/uploads

