spring.application.name=crud_springb_angular

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/crud_spring_angular_02
spring.datasource.username=${DB_USERNAME_POSTGRES}
spring.datasource.password=${DB_PASSWORD_POSTGRES}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.max-file-size=64MB
spring.servlet.multipart.max-request-size=64MB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=${SECURITY_USERNAME}
spring.security.user.password=${SECURITY_PASSWORD}

image.upload-dir=/home/brainiac/Documents/javaProjects/crudSpringBootAngular_imagens_02/backend/crud_springb_angular/uploads

